CataphTEBUnitPoolData = {
    -- Default
    wh_main_sc_teb_teb = {
		Units = {
			til_pavise = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_greatswords = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_guard = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_light_cannon = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_sartosa = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_carabineers = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_ducale = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_royal = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_conqui_foot = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_conqui = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_cav = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_kotrs = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_HA = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_archers = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_knights = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_heavy_cav = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_light_cav = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_rangers = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_mercs = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			emp_halb_bor = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_cannon_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_organ_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_warriors_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_warriors2h_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_rangers_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_pavise_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_broken_lances_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_ducale_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_conqui_foot_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_cav_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_mercs_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_conqui_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			emp_halb_te = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
		},
    },
}