CataphTEBUnitPoolData = {
    -- Default
    wh_main_sc_teb_teb = {
		Units = {
			-- Disable unused vanilla empire units
			--[[wh_dlc04_emp_inf_free_company_militia_0 = false,
			wh_dlc04_emp_inf_flagellants_0 = false,
			wh_dlc04_emp_cav_knights_blazing_sun_0 = false,
			wh_main_emp_art_helblaster_volley_gun = false,
			wh_main_emp_art_helstorm_rocket_battery = false,
			wh_main_emp_cav_demigryph_knights_0 = false,
			wh_main_emp_cav_demigryph_knights_1 = false,
			wh_main_emp_cav_empire_knights = false,
			wh_main_emp_cav_reiksguard = false,
			wh_main_emp_cav_outriders_0 = false,
			wh_main_emp_cav_outriders_1 = false,
			wh_main_emp_cav_pistoliers_1 = false,--]]
			-- Modified vanilla
			wh_main_emp_inf_halberdiers = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 40,
				RequiredGrowthForReplenishment = 20,
			},
			til_pavise = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_pike = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 40,
				RequiredGrowthForReplenishment = 20,
			},
			til_greatswords = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_guard = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_light_cannon = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_sartosa = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_carabineers = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_ducale = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_royal = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_conqui_foot = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_conqui = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_cav = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_kotrs = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_HA = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_archers = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 20,
			},
			bor_rangers = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 20,
			},
			bor_knights = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 10,
			},
			bor_heavy_cav = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
			},
			bor_light_cav = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 25,
			},
			bor_hop = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 35,
			},
			bor_mercs = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			emp_halb_bor = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_cannon_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_organ_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_warriors_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_warriors2h_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			dwf_rangers_teb = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			teb_paymaster = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_pavise_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_broken_lances_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			til_ducale_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_conqui_foot_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_cav_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			bor_mercs_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			est_conqui_col = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			emp_halb_te = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
		},
    },
}