ChaosUnitPoolData = {
    -- Default
	wh_main_sc_chs_chaos = {
		Units = {
			wh_dlc01_chs_inf_forsaken_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 20,
			},
			wh_dlc01_chs_mon_dragon_ogre_shaggoth = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
				IgnoreReplenishmentPenalties = true,
			},
			wh_dlc01_chs_mon_dragon_ogre = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 50,
			},
			wh_dlc01_chs_mon_trolls_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_mon_trolls = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 35,
			},
			wh_dlc06_chs_cav_marauder_horsemasters_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 30,
			},
			wh_dlc06_chs_feral_manticore = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
				IgnoreReplenishmentPenalties = true,
			},
			wh_dlc06_chs_inf_aspiring_champions_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_cav_chaos_chariot = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc01_chs_cav_gorebeast_chariot = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_art_hellcannon = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
			},
			wh_main_chs_cav_chaos_knights_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 15,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_cav_chaos_knights_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 5,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_cav_marauder_horsemen_0 = {
				StartingReserveCap = 1,
				StartingReserves = 100,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_chs_cav_marauder_horsemen_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_chs_inf_chaos_marauders_0 = {
				StartingReserveCap = 2,
				StartingReserves = 200,
				UnitGrowth = 40,
				RequiredGrowthForReplenishment = 20,
			},
			wh_main_chs_inf_chaos_marauders_1 = {
				StartingReserveCap = 1,
				StartingReserves = 0,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 20,
			},
			wh_main_chs_inf_chaos_warriors_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_inf_chaos_warriors_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 15,
				RequiredGrowthForReplenishment = 35,
			},
			wh_dlc01_chs_inf_chaos_warriors_2 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 15,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_inf_chosen_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_inf_chosen_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 40,
			},
			wh_dlc01_chs_inf_chosen_2 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 40,
			},
			wh_main_chs_mon_chaos_spawn = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
			},
			wh_main_chs_mon_chaos_warhounds_0 = {
				StartingReserveCap = 1,
				StartingReserves = 100,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_chs_mon_chaos_warhounds_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 25,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_chs_mon_giant = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 50,
				IgnoreReplenishmentPenalties = true,
			},
		},
	},
}