EmpireUnitPoolData = {
    -- Default
    wh_main_sc_emp_empire = {
		Units = {
			wh2_dlc13_emp_inf_archers_0 = {
				StartingReserveCap = 2,
				StartingReserves = 100,
				UnitGrowth = 40,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Building", },
			},
			wh_dlc04_emp_cav_knights_blazing_sun_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Diplomacy", },
			},
			wh_dlc04_emp_inf_flagellants_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 20,
				RecruitmentArchetypes = { "Building", },
			},
			wh_dlc04_emp_inf_free_company_militia_0 = {
				StartingReserveCap = 2,
				StartingReserves = 100,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 20,
				RecruitmentArchetypes = { "Building", },
			},
			wh2_dlc13_emp_veh_war_wagon_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 25,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Building", },
			},
			wh2_dlc13_emp_veh_war_wagon_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_art_great_cannon = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_art_helblaster_volley_gun = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 50,
				RecruitmentArchetypes = { "Diplomacy", },
			},
			wh_main_emp_art_helstorm_rocket_battery = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Building", "Diplomacy", },
			},
			wh_main_emp_art_mortar = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 25,
				RecruitmentArchetypes = { "Building", "Diplomacy", },
			},
			wh_main_emp_cav_demigryph_knights_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Diplomacy", },
			},
			wh_main_emp_cav_demigryph_knights_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Diplomacy", },
			},
			wh_main_emp_cav_empire_knights = {
				StartingReserveCap = 1,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 25,
				RecruitmentArchetypes = { "Diplomacy", },
			},
			wh_main_emp_cav_outriders_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_cav_outriders_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_cav_pistoliers_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Diplomacy", },
			},
			wh_main_emp_cav_reiksguard = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Diplomacy", },
			},
			wh_main_emp_inf_crossbowmen = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 25,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_inf_greatswords = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Diplomacy", },
			},
			wh_main_emp_inf_halberdiers = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 25,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_inf_handgunners = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 10,
				RequiredGrowthForReplenishment = 25,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_inf_spearmen_0 = {
				StartingReserveCap = 1,
				StartingReserves = 100,
				UnitGrowth = 40,
				RequiredGrowthForReplenishment = 20,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_inf_spearmen_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 20,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_inf_swordsmen = {
				StartingReserveCap = 1,
				StartingReserves = 100,
				UnitGrowth = 30,
				RequiredGrowthForReplenishment = 25,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_veh_luminark_of_hysh_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 0,
				RecruitmentArchetypes = { "Building", },
			},
			wh_main_emp_veh_steam_tank = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 0,
				RecruitmentArchetypes = { "Diplomacy", },
			},
		},
	},

    -- Major faction
    wh_main_emp_empire = {
        Units = {
            wh_main_emp_cav_reiksguard = {
				StartingReserveCap = 1,
				StartingReserves = 100,
				UnitGrowth = 20,
				RequiredGrowthForReplenishment = 35,
				RecruitmentArchetypes = { "Diplomacy", },
            },
        },
    },
}