NorscaUnitPoolData = {
    -- Default
    wh_main_sc_nor_norsca = {
		Units = {
			wh_dlc08_nor_cav_marauder_horsemasters_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_feral_manticore = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 0,
			},
			wh_dlc08_nor_inf_marauder_berserkers_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_inf_marauder_champions_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_inf_marauder_champions_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_inf_marauder_hunters_0 = {
				StartingReserveCap = 3,
				StartingReserves = 200,
				UnitGrowth = 50,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_inf_marauder_hunters_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_inf_marauder_spearman_0 = {
				StartingReserveCap = 5,
				StartingReserves = 300,
				UnitGrowth = 50,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_mon_fimir_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_mon_fimir_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_mon_frost_wyrm_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 0,
			},
			wh_dlc08_nor_mon_norscan_giant_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 0,
			},
			wh_dlc08_nor_mon_norscan_ice_trolls_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_mon_skinwolves_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_mon_skinwolves_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_mon_war_mammoth_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 0,
			},
			wh_dlc08_nor_mon_war_mammoth_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 0,
			},
			wh_dlc08_nor_mon_war_mammoth_2 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 0,
			},
			wh_dlc08_nor_mon_warwolves_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_dlc08_nor_veh_marauder_warwolves_chariot_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_nor_cav_chaos_chariot = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_nor_cav_marauder_horsemen_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_nor_cav_marauder_horsemen_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_nor_inf_chaos_marauders_0 = {
				StartingReserveCap = 6,
				StartingReserves = 400,
				UnitGrowth = 50,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_nor_inf_chaos_marauders_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_nor_mon_chaos_trolls = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_nor_mon_chaos_warhounds_0 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
			wh_main_nor_mon_chaos_warhounds_1 = {
				StartingReserveCap = 0,
				StartingReserves = 0,
				UnitGrowth = 0,
				RequiredGrowthForReplenishment = 25,
			},
		},
	},
}